### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by themcgamer1986** [asimhsidd/MMM-MP3Player#2]
not working with the latest version:

App threw an error during load
Error: The module '/home/pi/MagicMirror/modules/MMM-MP3Player/node_modules/usb/src/binding/usb_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MP3Player/node_modules/usb/usb.js:5:38)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MP3Player/node_modules/usb/usb.js:408:3)
Whoops! There was an uncaught exception...
Error: The module '/home/pi/MagicMirror/modules/MMM-MP3Player/node_modules/usb/src/binding/usb_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MP3Player/node_modules/usb/usb.js:5:38)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MP3Player/node_modules/usb/usb.js:408:3)

+ when npm install of npm rebuild it doesnt find the right dependencys anymore and screws up

**Comment by themcgamer1986** [comment]
got it fixed by switching my node to version 57 but the compile still didnt work on the dependencys. so i installed it manually.


it works on mirror boot with the stick inserted. but still fails to recognize the sick on the fly when the mirror is in working state

**Comment by themcgamer1986** [comment]
i think its the usb-node the latest wont install anymore with any node version it gets stuck on 404 in the dependancy github page

**Comment by theramez** [comment]
same here not working with exact error
